name: Build QAuxiliary

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug 
        # 或者 ./gradlew :app:synthesizeDistReleaseApksCI 

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: QAuxiliary-APK
          path: app/build/outputs/apk/debug/  # 修改为你实际的 APK 输出路径
