name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake ccache

    - name: Download and set up Android SDK and NDK
      run: |
        mkdir -p "$ANDROID_HOME"
        cd "$ANDROID_HOME"
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
        unzip -q commandlinetools-linux-8092744_latest.zip
        yes | ./cmdline-tools/bin/sdkmanager --sdk_root="$ANDROID_HOME" "platforms;android-34" "build-tools;34.0.0" "ndk;$NDK_VERSION" "cmake;$CMAKE_VERSION"

    - name: Export environment variables
      run: |
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "NDK_VERSION=${{ env.NDK_VERSION }}" >> $GITHUB_ENV
        echo "CMAKE_VERSION=${{ env.CMAKE_VERSION }}" >> $GITHUB_ENV

    - name: Build project
      run: |
        ./gradlew :app:assembleDebug

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-files
        path: |
          app/build/outputs/apk/debug/
          app/build/outputs/bundle/debug/

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      NDK_VERSION: 25.2.9519653
      CMAKE_VERSION: 3.22.1
