name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake ninja-build ccache

      - name: Download and install Android SDK & NDK
        # 使用 actions/setup-android@v3 或自定义脚本下载和安装特定版本的 SDK 和 NDK

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with ccache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.4.2'
          arguments: :app:assembleDebug -PccacheExecutablePath=$(which ccache)

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/
